### ISSUE TITLE
Conflict issues when compiling

### ISSUE THREAD

**Issue by aakashsharan** [michael-read/sensor-data-scala-proto-grpc#5]
/Users/aakash/.sdkman/candidates/java/11.0.10.hs-adpt/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -Didea.managed=true -Dfile.encoding=UTF-8 -Didea.installation.dir=/Applications/IntelliJ IDEA CE.app/Contents -jar /Users/aakash/Library/Application Support/JetBrains/IdeaIC2021.1/plugins/Scala/launcher/sbt-launch.jar
[info] welcome to sbt 1.5.5 (AdoptOpenJDK Java 11.0.10)
[info] loading global plugins from /Users/aakash/.sbt/1.0/plugins
[info] loading settings for project sensor-data-scala-proto-grpc-master-build from cloudflow-plugins.sbt,plugins.sbt ...
[info] loading project definition from /Users/aakash/tech/cloudflow/workspace/sensor-data-scala-proto-grpc-master/project
[error] java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* com.thesamet.scalapb:compilerplugin_2.12:0.11.3 (early-semver) is selected over 0.10.2
[error] 	    +- com.lightbend.akka.grpc:sbt-akka-grpc:2.0.0 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.11.3)
[error] 	    +- com.lightbend.akka.grpc:akka-grpc-codegen_2.12:2.0.0 (depends on 0.11.3)
[error] 	    +- com.lightbend.cloudflow:sbt-cloudflow:2.2.2 (sbtVersion=1.0, scalaVersion=2.12) (depends on 0.10.2)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:89)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3678)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* com.thesamet.scalapb:compilerplugin_2.12:0.11.3 (early-semver) is selected over 0.10.2
[error] 	    +- com.lightbend.akka.grpc:sbt-akka-grpc:2.0.0 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.11.3)
[error] 	    +- com.lightbend.akka.grpc:akka-grpc-codegen_2.12:2.0.0 (depends on 0.11.3)
[error] 	    +- com.lightbend.cloudflow:sbt-cloudflow:2.2.2 (sbtVersion=1.0, scalaVersion=2.12) (depends on 0.10.2)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel

**Comment by michael-read** [comment]
There appears to be a bug in SBT 1.5 that's being exposed with the Akka gRPC 2.0 version. Recommend moving back to SBT 1.4.9, by modifying `project/build.properties` with:
```
sbt.version=1.4.9
```
You'll also need to comment out the following line in the `build.sbt` file:
```
ThisBuild / evictionErrorLevel := Level.Info
```
